version: '3.1'

services:

  mongo:
    image: mongo:4.2.12
    container_name: investments-portfolio-mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker/mongodb/initData:/docker-entrypoint-initdb.d
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: CTT6u;_74r&*?UcM

  mongo-express:
    image: mongo-express
    container_name: investments-portfolio-mongo-express
    restart: always
    ports:
      - 9000:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: CTT6u;_74r&*?UcM